---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-srv
  template:
    metadata:
      labels:
        app: dispatcher-srv
    spec:
      containers:
      - name: dispatcher
        image: jadilet/dispatcher
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          value: "b-88178cf5-588b-435d-a72f-a0d562d9d919.mq.eu-central-1.amazonaws.com"
        - name: RABBITMQ_PORT
          value: "5671"
        - name: RABBITMQ_USER
          value: "test"
        - name: RABBITMQ_PASSWORD
          value: "testingtesting"
        - name: GRPC_DRIVERMANAGEMENT_SRV_PORT
          value: "50052"
        - name: GRPC_LOCATION_SRV_PORT
          value: "50051"
        - name: DISPATCHER_RADIUS
          value: "5"
