---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-srv
  template:
    metadata:
      labels:
        app: trip-srv
    spec:
      containers:
      - name: tripmanagement
        image: jadilet/tripmanagement
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: "200Mi"
          requests:
            cpu: 200m
            memory: "64Mi"
        env:
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DBNAME
          value: "tripmanagement"
        - name: MYSQL_PROTOCOL
          value: "tcp"
        - name: MYSQL_MASTER_HOST
          value: "taxihailing.cbiommknu3sn.eu-central-1.rds.amazonaws.com"
        - name: MYSQL_MASTER_PORT
          value: "3306"
        - name: MYSQL_SLAVE_HOST
          value: "taxihailing.cbiommknu3sn.eu-central-1.rds.amazonaws.com"
        - name: MYSQL_SLAVE_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "my-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "vZv1kaB7V7"
        - name: RABBITMQ_PROTOCOL
          value: amqp

---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip-srv
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer