apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trip-srv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trip-srv
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50