---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-srv
  template:
    metadata:
      labels:
        app: trip-srv
    spec:
      containers:
      - name: tripmanagement
        image: jadilet/tripmanagement
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_DBNAME
          value: "tripmanagement"
        - name: MYSQL_PROTOCOL
          value: "tcp"
        - name: MYSQL_MASTER_HOST
          value: "taxihailing.cbiommknu3sn.eu-central-1.rds.amazonaws.com"
        - name: MYSQL_MASTER_PORT
          value: "3306"
        - name: MYSQL_SLAVE_HOST
          value: "taxihailing.cbiommknu3sn.eu-central-1.rds.amazonaws.com"
        - name: MYSQL_SLAVE_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "b-88178cf5-588b-435d-a72f-a0d562d9d919.mq.eu-central-1.amazonaws.com"
        - name: RABBITMQ_PORT
          value: "5671"
        - name: RABBITMQ_USER
          value: "test"
        - name: RABBITMQ_PASSWORD
          value: "testingtesting"

---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip-srv
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer