apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drvmanagement-srv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drvmanagement-srv
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50