---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drvmanagement-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drvmanagement-srv
  template:
    metadata:
      labels:
        app: drvmanagement-srv
    spec:
      containers:
      - name: drivermanagement
        image: jadilet/drivermanagement:0.0.1
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_DBNAME
          value: "drivermanagement_db"
        - name: MYSQL_PROTOCOL
          value: "tcp"
        - name: MYSQL_MASTER_HOST
          value: "mysql.drivermng-mysql"
        - name: MYSQL_MASTER_PORT
          value: "3306"
        - name: MYSQL_SLAVE_HOST
          value: "mysql-read.drivermng-mysql"
        - name: MYSQL_SLAVE_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "rabbitmq.test-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: GRPC_DRIVERMANAGEMENT_SRV_PORT
          value: "50052"

---
apiVersion: v1
kind: Service
metadata:
  name: drvmanagement-service
spec:
  selector:
    app: drvmanagement-srv
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: tcp
      port: 50052
      targetPort: 50052
  type: LoadBalancer