---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drvmanagement-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drvmanagement-srv
  template:
    metadata:
      labels:
        app: drvmanagement-srv
    spec:
      containers:
      - name: drivermanagement
        image: jadilet/drivermanagement
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: "200Mi"
          requests:
            cpu: 200m
            memory: "64Mi"
        env:
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DBNAME
          value: "drivermanagement"
        - name: MYSQL_PROTOCOL
          value: "tcp"
        - name: MYSQL_MASTER_HOST
          value: "taxihailing.cbiommknu3sn.eu-central-1.rds.amazonaws.com"
        - name: MYSQL_MASTER_PORT
          value: "3306"
        - name: MYSQL_SLAVE_HOST
          value: "taxihailing.cbiommknu3sn.eu-central-1.rds.amazonaws.com"
        - name: MYSQL_SLAVE_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "my-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "vZv1kaB7V7"
        - name: GRPC_DRIVERMANAGEMENT_SRV_PORT
          value: "50052"
        - name: RABBITMQ_PROTOCOL
          value: amqp
        - name: GRPC_LOCATION_SRV_PORT
          value: "50051"
        - name: GRPC_LOCATION_SRV_NAME
          value: "location-service"

---
apiVersion: v1
kind: Service
metadata:
  name: drvmanagement-service
spec:
  selector:
    app: drvmanagement-srv
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: tcp
      port: 50052
      targetPort: 50052
  type: LoadBalancer