apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: location-grpc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location-grpc
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50