---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-grpc
  template:
    metadata:
      labels:
        app: location-grpc
    spec:
      containers:
      - name: location
        image: jadilet/location
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "my-redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USER
          value: ""
        - name: REDIS_PASSWORD
          value: "FlVfk7QI7D"
        - name: GRPC_LOCATION_SRV_PORT
          value: "50051"
        - name: REDIS_DB
          value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  type: NodePort
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: location-grpc